### ISSUE TITLE
Touchpad not seen as trackpad under pref pane but as a mouse with no scrolling.

### ISSUE THREAD

**Issue by Mi6simpatico** [influenist/Mi-NB-Gaming-Laptop-MacOS#1]
The touchpad is seen as a mouse in system preferences, without the two fingers scrolling gesture, even if using latest VoodooI2C with satellite kext and proper DSDT patches from VoodooI2C repo installation walkthrough. Maybe it is due to a bug imputable on VoodooI2C itself.

**Comment by influenist** [comment]
Hi @Mi6simpatico thank you for the feedback. This is due to the fact that from 2.0 and above multitouch is not supported by alexandred/VoodooI2C. Sadly we need to watch for support on this matter.

**Comment by influenist** [comment]
Hi, @Mi6simpatico the latest release includes multi-touch! 

https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/releases/tag/v1-1-hs-10.13.6

**Comment by influenist** [comment]
https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/commit/89b9bd4e0d42b69b72bdfc59d177bc5daf6a6de9Full support has been fixed in the latest commit
