### ISSUE TITLE
search to solder bluetooth

### ISSUE THREAD

**Issue by johnnync13** [influenist/Mi-NB-Gaming-Laptop-MacOS#12]
I have wifi and bluetooth on taobao but i'm searching where to solder

**Comment by influenist** [comment]
Hi @johnnync13, please take a look at the photo:
![e6b2a1bbf46b818129eeaedd88e889fb](https://user-images.githubusercontent.com/22964559/69886207-296a5f00-12e1-11ea-999f-27f841cb2ead.jpg)

Note this is NB PRO. In our case its located below the heatsink cover. Marked LTE. See picture:
![IMG_20180324_110811_HHT](https://user-images.githubusercontent.com/22964559/69886457-51a68d80-12e2-11ea-9918-d0f29ba9c347.jpg)

On TaoBao the exact solder Pins are noted. Please take a look there if you can see it. If not let me know, I'll contact the seller for you.
