### ISSUE TITLE
unbootable EFI/EFIOC 

### ISSUE THREAD

**Issue by zzz6839** [influenist/Mi-NB-Gaming-Laptop-MacOS#20]
@johnnync13 
Hi, I've tried several versions of your EFI/EFIOC and none of them was able to boot into installation for 10.15.4 MAC OS(either no bootable device in BIOS or no installation option on clover menu), however, the @influenist version for 14.3 is working but incompatible for Catalina(frozen in the installation without progress bar).

I'm using M3-7Y30 model Xiaomi Air.

**Comment by zengchencn** [comment]
You need a updated version of WhateverGreen

**Comment by johnnync13** [comment]
@zzz6839 @zengchencn  10.15.4 need latest version of Clover and WhateverGreen
see this: https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/pull/19

**Comment by zengchencn** [comment]
> @zzz6839 @zengchencn 10.15.4 need latest version of Clover and WhateverGreen
> see this: #19

Thanks a lot! You've been really helpful!

**Comment by johnnync13** [comment]
@zengchencn @zzz6839 now trackpad not needed rebuild cache and works on installation too

**Comment by zzz6839** [comment]
Thank you!!!!!!!!! I will test it later.

**Comment by zzz6839** [comment]
@johnnync13 There is no boot option for EFIOC in BIOS, but the good news is the installation is working but the trackpad isn't working on the installation.

**Comment by johnnync13** [comment]
You should use clover version first. There are bugs on openCore

**Comment by zzz6839** [comment]
@johnnync13 Thanks for your instruction! But the trackpad isn't working somehow.

**Comment by johnnync13** [comment]
Take photo on hackintool extensions

**Comment by zzz6839** [comment]
> Take photo on hackintool extensions

It's not working on installation, sorry for didn't mention that

**Comment by johnnync13** [comment]
Soon, submodule synaptics will rebase
