### ISSUE TITLE
The touchpad does not work after getting out of sleep

### ISSUE THREAD

**Issue by MarshalX** [influenist/Mi-NB-Gaming-Laptop-MacOS#3]
After each exit from sleep, the touchpad stops responding. The system will remain fully operational. It can be controlled from the keyboard. This bug was noticed in Mac OS 10.14.2 and 10.13.6.

Thanks for the work you've done!

**Comment by MarshalX** [comment]
The problem only concerns the touchpad. Usb mouse works

**Comment by influenist** [comment]
This is a known issues, which is caused by the VoodooI2C satellite. Please remove it from your EFI folder "VoodooI2CSynaptics.kext" 

After your sleep problems etc will resolve, yet please note you will lose mulit-touch on the trackpad.

**Comment by finner** [comment]
@influenist any chance you can help me get multi gestures work on air 13 2016 version? I think it uses the same synaptics trackpad like the 12inch model.

**Comment by influenist** [comment]
@finner Do you know your Synaptics device name? Please check ioRegistryExplorer as shown in the screen: 

<img width="740" alt="screen shot 2019-01-07 at 18 03 27" src="https://user-images.githubusercontent.com/22964559/50781818-a1353280-12a6-11e9-9616-4e1ec9e11fb8.png">

**Comment by finner** [comment]
Cannot find it because it loads as ps2trackpad 1.9.2

**Comment by influenist** [comment]
Do you boot with voodooI2C.kext?

**Comment by finner** [comment]
voodooI2C.kext is inside clover folder but I dont think its being loaded since trackpad works (basic functions) even when voodooI2C and VoodooHID kexts are missing

**Comment by MarshalX** [comment]
> This is a known issues, which is caused by the VoodooI2C satellite. Please remove it from your EFI folder "VoodooI2CSynaptics.kext"
> 
> After your sleep problems etc will resolve, yet please note you will lose mulit-touch on the trackpad.

No solution without losing multitouch? This is too much price for a sleep...

**Comment by MarshalX** [comment]
Francescobabbaro found the solution! [Post`s url](https://www.tonymacx86.com/threads/guide-xiaomi-notebook-air-12-5-kabylake-high-sierra-10-13-1.236258/page-6#post-1905978). 

You need to install the last [VoodooI2C](https://github.com/alexandred/VoodooI2C/releases) and replace IOPropertyMatch -> name in info.plist of VoodooI2CSynaptics package on “SYNA3105”.

Ready file with edits: [VoodooI2CSynaptics.kext.zip](https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/files/2848354/VoodooI2CSynaptics.kext.zip)

**Comment by influenist** [comment]
Solved in the latest release which is published today https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/commit/7a08af2a05e9aa24d7797f0c399e4d1439e12f83
