### ISSUE TITLE
HiDPI not works

### ISSUE THREAD

**Issue by johnnync13** [influenist/Mi-NB-Gaming-Laptop-MacOS#4]
@influenist On my Xiaomi mi Air i7-8550u not works.I choose 4 option on your script
[DarwinDumper.zip](https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/files/2730412/DarwinDumper.zip)

**Comment by Mateo1234454545** [comment]
Same here.
Is it possible to add 1680x945 HIDPI resolution , too?
Thanks.

**Comment by influenist** [comment]
@johnnync13 thats for the 13inch right, which release exactly? Mateo1234454 also tell me your version of the NB Air / Pro & CPU.

**Comment by Mateo1234454545** [comment]
It is for Mi NoteBook Pro 15 - Space Gray with i5-8250u.

**Comment by johnnync13** [comment]
@influenist I have Xiaomi Mi Air i7-8550u

**Comment by influenist** [comment]
Hi @johnnync13 & @Mateo1234454545 
I'll come with an update soon on the HiDPI script soon. Today I updated to Mojave and addressed the issues in the script.  

Could you provide me with your desired resolutions, DisplayProductID and DisplayVendorID?

Most-likely your DisplayVendorID is 9e5. For the Mi Air 12.5 the DisplayProductID is 691.

**Comment by johnnync13** [comment]
Hackintool has the script of hidpi now

**Comment by influenist** [comment]
Hi Mateo, out of the box kext will be to the next release.

**Comment by AlexRuck** [comment]
Thank you for your hard work. It work's like e charm. Hope the HiDPI kext will come soon. 
One question. Will you also support the new mi air 12.5 with the m3 - 8100Y processor?
