### ISSUE TITLE
Can't boot without KernelPM enabled

### ISSUE THREAD

**Issue by francescobabbaro** [influenist/Mi-NB-Gaming-Laptop-MacOS#5]
Thanks for your latest release! I noticed that in the config.plist, KernelPM isn't enabled like in the previous release and without it notebook doesn't boot (enabling it I have no problem).

**Comment by influenist** [comment]
Which CPU do you have? Perhaps you have got any old kext in /L*/E*? If so, please remove them.

Kernel PM and all other power options have been removed as it is handled by MacOS natively via kext CPUFriend and CPUFrienddataprovider. CPU should idle now at 600mhz.

**Comment by francescobabbaro** [comment]
My CPU is the 7y30. 
I believe that I added no kexts in that folder, but if you tell me that the system should boot without that patch, I'll try with a new clean installation.

**Comment by influenist** [comment]
Reinstall should not be needed. Do you have Gitter? I would like to check your install. 

Regarding the frequency, 600 mhz is exceptional under low load.

**Comment by francescobabbaro** [comment]
I don't know how gitter works in details, I used it one time, but yes, tell me what to do.

**Comment by influenist** [comment]
@francescobabbaro please open up terminal and provide the output of:

`sudo ls -lah /L*/E*`
`sudo ls -lah /S*/L*/E*`

Mount your EFI
`sudo ls -lah /Volumes/EFI/EFI/CLOVER/kexts/Other/`

`sudo ls -lah /Volumes/EFI/EFI/CLOVER/kext/`

**Comment by francescobabbaro** [comment]
Sorry, I'm not at home now, I'll do it tomorrow soon as possible. Thanks for the support, I really appreciate your work.

**Comment by francescobabbaro** [comment]
Sorry for the waiting: this is a txt file with the terminal outputs of the commands you said me.
[Terminal output.txt](https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/files/2935647/Terminal.output.txt)

**Comment by influenist** [comment]
Please drop the file and try to boot again:
`sudo rm /Volumes/EFI/EFI/ACPI/patched/SSDT-PluginType1.aml`

**Comment by MarshalX** [comment]
My output: [output.txt](https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/files/2937367/output.txt)


> Please drop the file and try to boot again:
> `sudo rm /Volumes/EFI/EFI/ACPI/patched/SSDT-PluginType1.aml`

I deleted the file `/Volumes/EFI/EFI/**CLOVER**/ACPI/patched/SSDT-PluginType1.aml`. Nothing changed

**Comment by francescobabbaro** [comment]
> Please drop the file and try to boot again:
> `sudo rm /Volumes/EFI/EFI/ACPI/patched/SSDT-PluginType1.aml`

Tried: unfortunately nothing changed :-(.

**Comment by influenist** [comment]
Please try:
[Mi-NB-Air-125-7y30-v1-2-1-mojave-10.14.3.zip](https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/files/2938970/Mi-NB-Air-125-7y30-v1-2-1-mojave-10.14.3.zip)

**Comment by JessicaJobs** [comment]
Still can't boot with the new one

**Comment by influenist** [comment]
In that case, please turn on the keepsyms flag in clover and provide the KP log.

**Comment by influenist** [comment]
@JessicaJobs which MacOS version are you on?

**Comment by MarshalX** [comment]
> In that case, please turn on the keepsyms flag in clover and provide the KP log.

Sorry, I really do not know where to get the log in text format
![log](https://user-images.githubusercontent.com/15520314/53955119-27c09180-40e9-11e9-88f4-fbe82ad4a499.png)

**Comment by influenist** [comment]
@MarshalX with kernelPM you are able to boot?

**Comment by MarshalX** [comment]
> @MarshalX with kernelPM you are able to boot?

Yes

**Comment by influenist** [comment]
I also noticed this same error when swapping my SSD to m5 variant. Please try and boot the laptop with adding the following file `/EFI/Clover/drivers64UEFI` and get back to me.


[OsxAptioFix2Drv-64.efi.zip](https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/files/2941271/OsxAptioFix2Drv-64.efi.zip)

**Comment by MarshalX** [comment]
> I also noticed this same error when swapping my SSD to the m5 12.5 variant. Please try and boot the laptop with adding the following file `/EFI/Clover/drivers64UEFI` and get back to me.
> 
> [OsxAptioFix2Drv-64.efi.zip](https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/files/2941271/OsxAptioFix2Drv-64.efi.zip)

Nothing changed

**Comment by influenist** [comment]
Ok, please remove it again. On basis of your screen it looks like RAM related issue. I removed the mapping from this config.plist. Please try it.
[config.plist.zip](https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/files/2941410/config.plist.zip)

**Comment by MarshalX** [comment]
> Ok, please remove it again. On basis of your screen it looks like RAM related issue. I removed the mapping from this config.plist. Please try it. If your systems hangs again, please try to make a clear picture of the verbose output. (-:
> 
> Thanks
> [config.plist.zip](https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/files/2941410/config.plist.zip)

Exactly the same output as above, except for one line.
`RegisterRestartDataProtocol: called.` **0x78271dd8**

**Comment by influenist** [comment]
Please revert and try the following in `/EFI/Clover/drivers64UEFI`

[EmuVariableUefi-64.efi.zip](https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/files/2941462/EmuVariableUefi-64.efi.zip)

**Comment by MarshalX** [comment]
> Please revert and try the following in `/EFI/Clover/drivers64UEFI`
> 
> [EmuVariableUefi-64.efi.zip](https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/files/2941462/EmuVariableUefi-64.efi.zip)

Revert old config?

**Comment by influenist** [comment]
Yes

**Comment by MarshalX** [comment]
> Please revert and try the following in `/EFI/Clover/drivers64UEFI`
> 
> [EmuVariableUefi-64.efi.zip](https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/files/2941462/EmuVariableUefi-64.efi.zip)

Nothing changed

**Comment by influenist** [comment]
Ok, ill test the later today on my m5 12.5 as I think its the same issue. Please boot with kernelPM for now.

**Comment by influenist** [comment]
@stevezhengshiqi maybe you got any clue on this issue?

**Comment by influenist** [comment]
@MarshalX Do you perhaps have an NVME installed in the second slot?

**Comment by MarshalX** [comment]
> @MarshalX Do you perhaps have an NVME installed in the second slot?

Not. I did not modify the laptop

**Comment by francescobabbaro** [comment]
> @MarshalX Do you perhaps have an NVME installed in the second slot?

I did not modify the laptop, too.
The strange fact is that the user of the #7, who have done a clean installation of 10.14.3, doesn't have our problem. I'd like to try a clean installation, because I did some modifications to EFI, kexts ecc since I installed the 10.14.1, although I think I revert back all the modifications, I could have forgotten something. 
Unfortunately, I don't have much time in this period and I use the laptop for university...

**Comment by influenist** [comment]
My install comes back from HS. So clean or not, that shouldn't be the issue here. Ur booting from USB, correct?

**Comment by francescobabbaro** [comment]
> My install comes back from HS. So clean or not, that shouldn't be the issue here. Ur booting from USB, correct?
> 
> I think it might optionally be BIOS related

No, I'm booting from SSD.
I remember that I wasn't able to boot the MacOS installation from USB with your EFI because I got the symbol of "prohibition" (I don't know what's the correct word in English). The same EFI folder worked perfectly booting by SSD after the installation of the system.

**Comment by influenist** [comment]
Which filesystem type do you guys use? APFS of HFS?

**Comment by MarshalX** [comment]
> My install comes back from HS. So clean or not, that shouldn't be the issue here. Ur booting from USB, correct?
> 
> I think it might optionally be BIOS related

My booting from USB is correct. 



> Which filesystem type do you guys use? APFS of HFS?

On Moaje we have way to use HFS? I use APFS

**Comment by francescobabbaro** [comment]
> Which filesystem type do you guys use? APFS of HFS?

APFS, too.
I tried with USB and the system boots perfectly.

**Comment by MarshalX** [comment]
Who can explain to me why we want to run systems without this patch (kernelPM)?

**Comment by MarshalX** [comment]
> > Which filesystem type do you guys use? APFS of HFS?
> 
> APFS, too.
> I tried with USB and the system boots perfectly.

Do not throw me. Are you sure you started from a flash drive? :D

**Comment by francescobabbaro** [comment]
> > > Which filesystem type do you guys use? APFS of HFS?
> > 
> > 
> > APFS, too.
> > I tried with USB and the system boots perfectly.
> 
> Do not throw me. Are you sure you started from a flash drive? :D

Sorry...I'm tired and my English is very bad. I've corrected the post.

**Comment by influenist** [comment]
Solved with latest release https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/releases/tag/v2-0-mojave-10.14.3. Seems some boards have loacked CPU MSR 0xE2. By removing the flag from the config clover auto detects if the patch is needed or not.

**Comment by influenist** [comment]
https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/commit/a57f0dd7f92b5e8db3324fd076d1dd3e2f554dc9
