### ISSUE TITLE
Resolution problem

### ISSUE THREAD

**Issue by leoleo49** [influenist/Mi-NB-Gaming-Laptop-MacOS#7]
The system UI is too small under 1080p
944p look good for the size but text display very badly.

Using HDDPI in 944p, everything look good but the computer very lag when scrolling, even in Microsoft word.
Do you have any better solution? 
Sorry for my bad English.
Thanks for your help.

**Comment by influenist** [comment]
Hi @leoleo49 

Which release are you booting from?

**Comment by leoleo49** [comment]
Hi,
i am using Mi notebook Air 12.5 7Y30
v1-2 release with Mojave 10.14.3.
Thanks for your response.

**Comment by influenist** [comment]
Are you experiencing this same issues as noted in https://github.com/influenist/Mi-NB-Gaming-Laptop-MacOS/issues/5 ?

**Comment by leoleo49** [comment]
Um........I don't think so.
There is no booting problem on my notebook.

**Comment by influenist** [comment]
Did you install the latest kext into /L*/E*?

**Comment by leoleo49** [comment]
What kext you mean?

**Comment by leoleo49** [comment]
I just install 10.14.3. And replace the EFI.

**Comment by influenist** [comment]
Regarding your issue. Please use the HDPI generator inside the hackintool from https://www.insanelymac.com/forum/topic/335018-hackintool-v196/.
