### ISSUE TITLE
 the keyboard can't  print Tilde sign

### ISSUE THREAD

**Issue by jmesyan** [influenist/Mi-NB-Gaming-Laptop-MacOS#9]
xiaomi my7 12.5inch with macos 10.14,
the keyboard can't  print Tilde sign(~),  output is § or ±, how to solve the problem ?

**Comment by francescobabbaro** [comment]
In keyboard settings, make sure that you have chosen "US international". Under the "keyboard" tab, click on "change keyboard type", after following the instructions (press the buttons near shift etc), at the end select "ANSI" and NOT "ISO". This should be the solution.

P.S. I use macOS in Italian and I don't know if the translation I've done is correct.

**Comment by jmesyan** [comment]
@francescobabbaro  I have use the ANSI type, but it doesn't work

**Comment by jmesyan** [comment]
@francescobabbaro  i change to iso type, it'ok, thanks
